/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 1.2 */
/* Sun Feb 09 16:51:32 2025 */

/* parameterized module instance */
I2C_UPDATE __ (.wb_clk_i( ), .wb_rst_i( ), .wb_cyc_i( ), .wb_stb_i( ), 
    .wb_we_i( ), .wb_adr_i( ), .wb_dat_i( ), .wb_dat_o( ), .wb_ack_o( ), 
    .i2c1_scl( ), .i2c1_sda( ), .i2c1_irqo( ), .wbc_ufm_irq( ));
