onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/clk
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/reset
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/t1us
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/t512us
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/t1ms
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/t2ms
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/t64ms
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/t1s
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/keep_alive_on_fault
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/dc_on_wait_complete
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/rt_critical_fail_store
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/fault_clear
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/pgd_so_far
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/s5dev_pwren_request
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/s5dev_pwrdis_request
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/any_pwr_fault_det
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/any_aux_vrm_fault
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/any_recov_fault
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/any_lim_recov_fault
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/any_non_recov_fault
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/p5v_stby_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_b_p0_33_s5_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_b_p1_33_s5_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_b_p0_18_s5_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_b_p1_18_s5_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/p3v3_stby_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/p12v_stby_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/p12v_efuse_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/p12v_ssd_efuse_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/p12v_p0_dimm_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/p12v_p1_dimm_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/p5v_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_c_p0_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_c_p1_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_d_vddio_p0_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_d_vddio_p1_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_d_soc_p0_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_d_soc_p1_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_d_p0_vddcore0_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_d_p1_vddcore0_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_d_p0_vddcore1_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_d_p1_vddcore1_pg
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/i_pwrgd_ocp0_nic_pwrgd
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/p5v_stby_en
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/p5v_stby_usb_en
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_b_p0_33_s5_en
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_b_p1_33_s5_en
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_b_p0_18_s5_en
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_b_p1_18_s5_en
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/power_supply_on
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/p5v_en
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/power_seq_sm
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/reg_grp_c_en
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/i_cpu_prsnt_n
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_b_p1_18_s5_fault_det
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/keep_alive_on_fault
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_c_p0_vdd11_en
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_c_p1_vdd11_en
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_d_p0_vddio_en
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_d_p1_vddio_en
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_d_p0_soc_en
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_d_p1_soc_en
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_d_p0_vddcore0_en
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_d_p1_vddcore0_en
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_d_p0_vddcore1_en
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/grp_d_p1_vddcore1_en
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/ocp_aux_en
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/ocp_main_en
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/o_p0_pwr_good
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/o_cpu_pwrok
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/o_rsmrst_n
add wave -noupdate /pwrseq_tb/pwrseq_slave_inst/reached_sm_wait_powerok
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {79152672 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 242
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {792320049 ps}
