/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.7 */
/* Thu Feb 06 21:45:10 2025 */

/* parameterized module instance */
pll_i25M_o50M_o25M __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
