[ActiveSupport PAR]
; Global primary clocks
GLOBAL_PRIMARY_USED = 2;
; Global primary clock #0
GLOBAL_PRIMARY_0_SIGNALNAME = clk_50m;
GLOBAL_PRIMARY_0_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_0_LOADNUM = 319;
; Global primary clock #1
GLOBAL_PRIMARY_1_SIGNALNAME = clk_25m;
GLOBAL_PRIMARY_1_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_1_LOADNUM = 137;
; # of global secondary clocks
GLOBAL_SECONDARY_USED = 4;
; Global secondary clock #0
GLOBAL_SECONDARY_0_SIGNALNAME = bmc_cpld_i2c_ram_u0/i2c_slave_bmc_u0/o_i2c_start;
GLOBAL_SECONDARY_0_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_0_LOADNUM = 22;
GLOBAL_SECONDARY_0_SIGTYPE = RST;
; Global secondary clock #1
GLOBAL_SECONDARY_1_SIGNALNAME = pon_reset_n;
GLOBAL_SECONDARY_1_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_1_LOADNUM = 19;
GLOBAL_SECONDARY_1_SIGTYPE = CE+RST;
; Global secondary clock #2
GLOBAL_SECONDARY_2_SIGNALNAME = bmc_cpld_i2c_ram_u0/i2c_slave_bmc_u0/w_i2c_command_1_i;
GLOBAL_SECONDARY_2_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_2_LOADNUM = 8;
GLOBAL_SECONDARY_2_SIGTYPE = CLK;
; Global secondary clock #3
GLOBAL_SECONDARY_3_SIGNALNAME = bmc_cpld_i2c_ram_u0/i2c_slave_bmc_u0/i2c_slave_basic0_u0/un1_w_rst_i;
GLOBAL_SECONDARY_3_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_3_LOADNUM = 44;
GLOBAL_SECONDARY_3_SIGTYPE = RST;
; I/O Bank 0 Usage
BANK_0_USED = 36;
BANK_0_AVAIL = 51;
BANK_0_VCCIO = 2.5V;
BANK_0_VREF1 = NA;
; I/O Bank 1 Usage
BANK_1_USED = 26;
BANK_1_AVAIL = 52;
BANK_1_VCCIO = 2.5V;
BANK_1_VREF1 = NA;
; I/O Bank 2 Usage
BANK_2_USED = 38;
BANK_2_AVAIL = 52;
BANK_2_VCCIO = 2.5V;
BANK_2_VREF1 = NA;
; I/O Bank 3 Usage
BANK_3_USED = 13;
BANK_3_AVAIL = 16;
BANK_3_VCCIO = 2.5V;
BANK_3_VREF1 = NA;
; I/O Bank 4 Usage
BANK_4_USED = 12;
BANK_4_AVAIL = 16;
BANK_4_VCCIO = 2.5V;
BANK_4_VREF1 = NA;
; I/O Bank 5 Usage
BANK_5_USED = 18;
BANK_5_AVAIL = 20;
BANK_5_VCCIO = 2.5V;
BANK_5_VREF1 = NA;
