setenv SIM_WORKING_FOLDER .
set newDesign 0
if {![file exists "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/pro/test_11/wea12/asda11/asda11.adf"]} { 
	design create asda11 "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/pro/test_11/wea12"
  set newDesign 1
}
design open "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/pro/test_11/wea12/asda11"
cd "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/pro/test_11/wea12"
designverincludedir -clear
designverincludedir "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" 
designverlibrarysim -PL -clear
designverlibrarysim -L -clear
designverlibrarysim -PL pmi_work
designverlibrarysim ovi_machxo3l
designverdefinemacro -clear
if {$newDesign == 0} { 
  removefile -Y -D *
}
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/bmc_i2c/i2c_slave_basic0.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/bmc_i2c/i2c_slave_bmc.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/bmc_i2c/bmc_cpld_i2c_ram.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/74LV165/pvt_gpi.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/edge_delay.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/nmi_clear.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/cmos_clear.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/ESPI_LINK/pcie_dync_alloc.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/bios_i2c/bios_cpld_i2c_ram.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/ESPI_LINK/pch_cpld_espi_ram.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/ESPI_LINK/espi_link.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/uart/mcio_uart_master.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Power_Fault/ERROR_CODE.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Power_Fault/fault_detectB_chklive.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Power_Fault/dimm_fail_event.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Pwr_seq/pwrseq_slave.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/edge_detect.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Pwr_seq/pwrseq_master.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/cpu_module.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Signal_Latch/Edge_Detect_SL.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Signal_Latch/Signal_Latch.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/cpu_thermtrip.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/lowpass_filter.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/system_rst.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Pwr_But_Ctrl/bmc_ctl_pwrbtn.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Pwr_But_Ctrl/Pwr_But_Ctrl.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/SGPIO_MASTER/p2s_slave.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/SGPIO_MASTER/s2p_master.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/synclib.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/IIC_Update/I2C_UPDATE.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/ClkDiv.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/ClkDivTree.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/timer_gen_50mhz.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/pon_reset.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/PLL/pll_i25M_o50M_o25M.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/BM_H13DSP_M_TOP.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/delay.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/extrst_evt_count.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/genCntr.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/MESSAGE_CONTROL.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Power_Fault/fault_detectA_chklive.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Power_Fault/Pwr_Error_Latch.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Power_Fault/Power_Fault.v"
addfile "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/74HC164/s2p_164.v"
vlib "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/pro/test_11/wea12/asda11/work"
set worklib work
adel -all
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/bmc_i2c/i2c_slave_basic0.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/bmc_i2c/i2c_slave_bmc.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/bmc_i2c/bmc_cpld_i2c_ram.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/74LV165/pvt_gpi.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/edge_delay.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/nmi_clear.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/cmos_clear.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/ESPI_LINK/pcie_dync_alloc.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/bios_i2c/bios_cpld_i2c_ram.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/ESPI_LINK/pch_cpld_espi_ram.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/ESPI_LINK/espi_link.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/uart/mcio_uart_master.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Power_Fault/ERROR_CODE.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Power_Fault/fault_detectB_chklive.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Power_Fault/dimm_fail_event.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Pwr_seq/pwrseq_slave.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/edge_detect.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Pwr_seq/pwrseq_master.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/cpu_module.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Signal_Latch/Edge_Detect_SL.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Signal_Latch/Signal_Latch.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/cpu_thermtrip.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/lowpass_filter.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/system_rst.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Pwr_But_Ctrl/bmc_ctl_pwrbtn.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Pwr_But_Ctrl/Pwr_But_Ctrl.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/SGPIO_MASTER/p2s_slave.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/SGPIO_MASTER/s2p_master.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/synclib.v"
vlog -dbg -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/IIC_Update/I2C_UPDATE.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/ClkDiv.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/ClkDivTree.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/timer_gen_50mhz.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/pon_reset.v"
vlog -dbg -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/PLL/pll_i25M_o50M_o25M.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/BM_H13DSP_M_TOP.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/delay.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/extrst_evt_count.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/genCntr.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/common/MESSAGE_CONTROL.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Power_Fault/fault_detectA_chklive.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Power_Fault/Pwr_Error_Latch.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/Power_Fault/Power_Fault.v"
vlog -dbg +incdir+"D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/include" -work work "D:/ODM MB SWITCH/MB/09/BM_H13DSP_M/rtl/source/74HC164/s2p_164.v"
module BM_H13DSP_M
vsim  +access +r BM_H13DSP_M   -PL pmi_work -L ovi_machxo3l
add wave *
run 1000ns
