/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.8.0.115.3 */
/* Module Version: 5.8 */
/* C:\lscc\diamond\3.8_x64\ispfpga\bin\nt64\scuba.exe -w -n ddr_generic -lang verilog -synth synplify -bus_exp 7 -bb -arch xo3c00f -type iol -mode out -io_type LVCMOS33 -width 1 -freq_in 50 -trioddr -gear 1 -clk sclk -aligned -del -1  */
/* Tue Apr 21 20:01:19 2020 */


`timescale 1 ns / 1 ps
module ddr_generic (clk, clkout, reset, sclk, tristate, dataout, dout)/* synthesis NGD_DRC_MASK=1 */;
    input wire clk;
    input wire reset;
    input wire tristate;
    input wire [1:0] dataout;
    output wire clkout;
    output wire sclk;
    output wire [0:0] dout;

    wire sclk_t;
    wire db0;
    wire da0;
    wire buf_clkout;
    wire scuba_vlo;
    wire scuba_vhi;
    wire clkos;
    wire clkop;
    wire tristateo;
    wire buf_douto0;

    OFS1P3DX Inst5_OFS1P3DX (.D(tristate), .SP(scuba_vhi), .SCLK(sclk_t), 
        .CD(reset), .Q(tristateo));

    OBZ Inst4_OBZ (.I(buf_clkout), .T(tristateo), .O(clkout))
             /* synthesis IO_TYPE="LVCMOS33" */;

    ODDRXE Inst3_ODDRXE0 (.D0(da0), .D1(db0), .SCLK(clkop), .RST(reset), 
        .Q(buf_douto0));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    ODDRXE Inst2_ODDRXE (.D0(scuba_vhi), .D1(scuba_vlo), .SCLK(clkos), .RST(reset), 
        .Q(buf_clkout));

    OBZ Inst1_OBZ0 (.I(buf_douto0), .T(tristateo), .O(dout[0]))
             /* synthesis IO_TYPE="LVCMOS33" */;

    assign sclk = clkop;
    assign sclk_t = clkop;
    assign db0 = dataout[1];
    assign da0 = dataout[0];
    assign clkos = clk;
    assign clkop = clk;


    // exemplar begin
    // exemplar attribute Inst4_OBZ IO_TYPE LVCMOS33
    // exemplar attribute Inst1_OBZ0 IO_TYPE LVCMOS33
    // exemplar end

endmodule
