/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.8.0.115.3 */
/* Module Version: 5.8 */
/* Tue Apr 21 20:01:19 2020 */

/* parameterized module instance */
ddr_generic __ (.clk( ), .clkout( ), .reset( ), .sclk( ), .tristate( ), 
    .dataout( ), .dout( ));
