/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.0.111.2 */
/* Module Version: 1.2 */
/* Mon Sep 13 19:51:31 2021 */

/* parameterized module instance */
efb_i2c __ (.wb_clk_i( ), .i2c1_scl( ), .i2c1_sda( ), .i2c1_irqo( ));
