/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.10.0.111.2 */
/* Module Version: 1.2 */
/* C:\lscc\diamond\3.10_x64\ispfpga\bin\nt64\scuba.exe -w -n efb_i2c -lang verilog -synth lse -bus_exp 7 -bb -type efb -arch xo3c00f -freq 25 -i2c1config -i2c1_freq 100 -i2c1_sa 1000001 -i2c1_addr 7 -dev 6900  */
/* Mon Sep 13 19:51:31 2021 */


`timescale 1 ns / 1 ps
module efb_i2c (wb_clk_i, i2c1_scl, i2c1_sda, i2c1_irqo)/* synthesis NGD_DRC_MASK=1 */;
    input wire wb_clk_i;
    output wire i2c1_irqo;
    inout wire i2c1_scl;
    inout wire i2c1_sda;

    wire scuba_vhi;
    wire i2c1_sdaoen;
    wire i2c1_sdao;
    wire i2c1_scloen;
    wire i2c1_sclo;
    wire i2c1_sdai;
    wire i2c1_scli;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    BB BB1_sda (.I(i2c1_sdao), .T(i2c1_sdaoen), .O(i2c1_sdai), .B(i2c1_sda));

    BB BB1_scl (.I(i2c1_sclo), .T(i2c1_scloen), .O(i2c1_scli), .B(i2c1_scl));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam EFBInst_0.UFM_INIT_FILE_FORMAT = "HEX" ;
    defparam EFBInst_0.UFM_INIT_FILE_NAME = "NONE" ;
    defparam EFBInst_0.UFM_INIT_ALL_ZEROS = "ENABLED" ;
    defparam EFBInst_0.UFM_INIT_START_PAGE = 0 ;
    defparam EFBInst_0.UFM_INIT_PAGES = 0 ;
    defparam EFBInst_0.DEV_DENSITY = "6900L" ;
    defparam EFBInst_0.EFB_UFM = "DISABLED" ;
    defparam EFBInst_0.TC_ICAPTURE = "DISABLED" ;
    defparam EFBInst_0.TC_OVERFLOW = "DISABLED" ;
    defparam EFBInst_0.TC_ICR_INT = "OFF" ;
    defparam EFBInst_0.TC_OCR_INT = "OFF" ;
    defparam EFBInst_0.TC_OV_INT = "OFF" ;
    defparam EFBInst_0.TC_TOP_SEL = "OFF" ;
    defparam EFBInst_0.TC_RESETN = "ENABLED" ;
    defparam EFBInst_0.TC_OC_MODE = "TOGGLE" ;
    defparam EFBInst_0.TC_OCR_SET = 32767 ;
    defparam EFBInst_0.TC_TOP_SET = 65535 ;
    defparam EFBInst_0.GSR = "ENABLED" ;
    defparam EFBInst_0.TC_CCLK_SEL = 1 ;
    defparam EFBInst_0.TC_MODE = "CTCM" ;
    defparam EFBInst_0.TC_SCLK_SEL = "PCLOCK" ;
    defparam EFBInst_0.EFB_TC_PORTMODE = "WB" ;
    defparam EFBInst_0.EFB_TC = "DISABLED" ;
    defparam EFBInst_0.SPI_WAKEUP = "DISABLED" ;
    defparam EFBInst_0.SPI_INTR_RXOVR = "DISABLED" ;
    defparam EFBInst_0.SPI_INTR_TXOVR = "DISABLED" ;
    defparam EFBInst_0.SPI_INTR_RXRDY = "DISABLED" ;
    defparam EFBInst_0.SPI_INTR_TXRDY = "DISABLED" ;
    defparam EFBInst_0.SPI_SLAVE_HANDSHAKE = "DISABLED" ;
    defparam EFBInst_0.SPI_PHASE_ADJ = "DISABLED" ;
    defparam EFBInst_0.SPI_CLK_INV = "DISABLED" ;
    defparam EFBInst_0.SPI_LSB_FIRST = "DISABLED" ;
    defparam EFBInst_0.SPI_CLK_DIVIDER = 1 ;
    defparam EFBInst_0.SPI_MODE = "MASTER" ;
    defparam EFBInst_0.EFB_SPI = "DISABLED" ;
    defparam EFBInst_0.I2C2_WAKEUP = "DISABLED" ;
    defparam EFBInst_0.I2C2_GEN_CALL = "DISABLED" ;
    defparam EFBInst_0.I2C2_CLK_DIVIDER = 1 ;
    defparam EFBInst_0.I2C2_BUS_PERF = "100kHz" ;
    defparam EFBInst_0.I2C2_SLAVE_ADDR = "0b1000001" ;
    defparam EFBInst_0.I2C2_ADDRESSING = "7BIT" ;
    defparam EFBInst_0.EFB_I2C2 = "DISABLED" ;
    defparam EFBInst_0.I2C1_WAKEUP = "DISABLED" ;
    defparam EFBInst_0.I2C1_GEN_CALL = "DISABLED" ;
    defparam EFBInst_0.I2C1_CLK_DIVIDER = 63 ;
    defparam EFBInst_0.I2C1_BUS_PERF = "100kHz" ;
    defparam EFBInst_0.I2C1_SLAVE_ADDR = "0b1000001" ;
    defparam EFBInst_0.I2C1_ADDRESSING = "7BIT" ;
    defparam EFBInst_0.EFB_I2C1 = "ENABLED" ;
    defparam EFBInst_0.EFB_WB_CLK_FREQ = "25.0" ;
    EFB EFBInst_0 (.WBCLKI(wb_clk_i), .WBRSTI(scuba_vlo), .WBCYCI(scuba_vlo), 
        .WBSTBI(scuba_vlo), .WBWEI(scuba_vlo), .WBADRI7(scuba_vlo), .WBADRI6(scuba_vlo), 
        .WBADRI5(scuba_vlo), .WBADRI4(scuba_vlo), .WBADRI3(scuba_vlo), .WBADRI2(scuba_vlo), 
        .WBADRI1(scuba_vlo), .WBADRI0(scuba_vlo), .WBDATI7(scuba_vlo), .WBDATI6(scuba_vlo), 
        .WBDATI5(scuba_vlo), .WBDATI4(scuba_vlo), .WBDATI3(scuba_vlo), .WBDATI2(scuba_vlo), 
        .WBDATI1(scuba_vlo), .WBDATI0(scuba_vlo), .PLL0DATI7(scuba_vlo), 
        .PLL0DATI6(scuba_vlo), .PLL0DATI5(scuba_vlo), .PLL0DATI4(scuba_vlo), 
        .PLL0DATI3(scuba_vlo), .PLL0DATI2(scuba_vlo), .PLL0DATI1(scuba_vlo), 
        .PLL0DATI0(scuba_vlo), .PLL0ACKI(scuba_vlo), .PLL1DATI7(scuba_vlo), 
        .PLL1DATI6(scuba_vlo), .PLL1DATI5(scuba_vlo), .PLL1DATI4(scuba_vlo), 
        .PLL1DATI3(scuba_vlo), .PLL1DATI2(scuba_vlo), .PLL1DATI1(scuba_vlo), 
        .PLL1DATI0(scuba_vlo), .PLL1ACKI(scuba_vlo), .I2C1SCLI(i2c1_scli), 
        .I2C1SDAI(i2c1_sdai), .I2C2SCLI(scuba_vlo), .I2C2SDAI(scuba_vlo), 
        .SPISCKI(scuba_vlo), .SPIMISOI(scuba_vlo), .SPIMOSII(scuba_vlo), 
        .SPISCSN(scuba_vlo), .TCCLKI(scuba_vlo), .TCRSTN(scuba_vlo), .TCIC(scuba_vlo), 
        .UFMSN(scuba_vhi), .WBDATO7(), .WBDATO6(), .WBDATO5(), .WBDATO4(), 
        .WBDATO3(), .WBDATO2(), .WBDATO1(), .WBDATO0(), .WBACKO(), .PLLCLKO(), 
        .PLLRSTO(), .PLL0STBO(), .PLL1STBO(), .PLLWEO(), .PLLADRO4(), .PLLADRO3(), 
        .PLLADRO2(), .PLLADRO1(), .PLLADRO0(), .PLLDATO7(), .PLLDATO6(), 
        .PLLDATO5(), .PLLDATO4(), .PLLDATO3(), .PLLDATO2(), .PLLDATO1(), 
        .PLLDATO0(), .I2C1SCLO(i2c1_sclo), .I2C1SCLOEN(i2c1_scloen), .I2C1SDAO(i2c1_sdao), 
        .I2C1SDAOEN(i2c1_sdaoen), .I2C2SCLO(), .I2C2SCLOEN(), .I2C2SDAO(), 
        .I2C2SDAOEN(), .I2C1IRQO(i2c1_irqo), .I2C2IRQO(), .SPISCKO(), .SPISCKEN(), 
        .SPIMISOO(), .SPIMISOEN(), .SPIMOSIO(), .SPIMOSIEN(), .SPIMCSN7(), 
        .SPIMCSN6(), .SPIMCSN5(), .SPIMCSN4(), .SPIMCSN3(), .SPIMCSN2(), 
        .SPIMCSN1(), .SPIMCSN0(), .SPICSNEN(), .SPIIRQO(), .TCINT(), .TCOC(), 
        .WBCUFMIRQ(), .CFGWAKE(), .CFGSTDBY());



    // exemplar begin
    // exemplar end

endmodule
