[ActiveSupport PAR]
; Global primary clocks
GLOBAL_PRIMARY_USED = 2;
; Global primary clock #0
GLOBAL_PRIMARY_0_SIGNALNAME = clk_50m;
GLOBAL_PRIMARY_0_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_0_LOADNUM = 765;
; Global primary clock #1
GLOBAL_PRIMARY_1_SIGNALNAME = clk_25m;
GLOBAL_PRIMARY_1_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_1_LOADNUM = 152;
; # of global secondary clocks
GLOBAL_SECONDARY_USED = 5;
; Global secondary clock #0
GLOBAL_SECONDARY_0_SIGNALNAME = mcpld_to_scpld_data_filter4;
GLOBAL_SECONDARY_0_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_0_LOADNUM = 11;
GLOBAL_SECONDARY_0_SIGTYPE = CE;
; Global secondary clock #1
GLOBAL_SECONDARY_1_SIGNALNAME = bmc_cpld_i2c_ram_u0/i2c_slave_bmc_u0/w_i2c_command_1_i;
GLOBAL_SECONDARY_1_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_1_LOADNUM = 8;
GLOBAL_SECONDARY_1_SIGTYPE = CLK;
; Global secondary clock #2
GLOBAL_SECONDARY_2_SIGNALNAME = bmc_cpld_i2c_ram_u0/i2c_slave_bmc_u0/o_i2c_start;
GLOBAL_SECONDARY_2_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_2_LOADNUM = 23;
GLOBAL_SECONDARY_2_SIGTYPE = RST;
; Global secondary clock #3
GLOBAL_SECONDARY_3_SIGNALNAME = bmc_cpld_i2c_ram_u0/i2c_slave_bmc_u0/i2c_slave_basic0_u0/un1_w_rst_i;
GLOBAL_SECONDARY_3_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_3_LOADNUM = 44;
GLOBAL_SECONDARY_3_SIGTYPE = RST;
; Global secondary clock #4
GLOBAL_SECONDARY_4_SIGNALNAME = inst_mb_to_slv_s2p/po5;
GLOBAL_SECONDARY_4_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_4_LOADNUM = 11;
GLOBAL_SECONDARY_4_SIGTYPE = CE;
; I/O Bank 0 Usage
BANK_0_USED = 63;
BANK_0_AVAIL = 84;
BANK_0_VCCIO = 3.3V;
BANK_0_VREF1 = NA;
; I/O Bank 1 Usage
BANK_1_USED = 66;
BANK_1_AVAIL = 84;
BANK_1_VCCIO = 3.3V;
BANK_1_VREF1 = NA;
; I/O Bank 2 Usage
BANK_2_USED = 77;
BANK_2_AVAIL = 84;
BANK_2_VCCIO = 3.3V;
BANK_2_VREF1 = NA;
; I/O Bank 3 Usage
BANK_3_USED = 24;
BANK_3_AVAIL = 28;
BANK_3_VCCIO = 3.3V;
BANK_3_VREF1 = NA;
; I/O Bank 4 Usage
BANK_4_USED = 24;
BANK_4_AVAIL = 24;
BANK_4_VCCIO = 3.3V;
BANK_4_VREF1 = NA;
; I/O Bank 5 Usage
BANK_5_USED = 31;
BANK_5_AVAIL = 32;
BANK_5_VCCIO = 3.3V;
BANK_5_VREF1 = NA;
