/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.7 */
/* Tue Nov 08 17:13:04 2022 */

/* parameterized module instance */
pll_i25M_o50M_o25M __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
